# GENERAL & NAVs
site_name: ImposterWho
# use_directory_urls: false
nav:
  - Home: index.md

# PLUGINS
plugins:
  - search
  # - offline
  - blog:
      blog_toc: true
  # - glightbox

# THEME
theme:
  name: material
  favicon: assets/img/favicon.ico
  language: en
  logo: assets/img/logo.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - toc.follow
    - navigation.indexes
    - announce.dismiss
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: green
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: white
      accent: indigo

# EXTRA
extra:
  mathjax: true
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/plexoio
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/plexoio
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/arellanofrank/
  consent:
    title: Consentimiento de las Cookies
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better. If you are seeing this offline,
      then you don't have to worry about anything.
    actions:
      - accept

# EXTENSIONS
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index:
        !!python/name:material.extensions.emoji.twemoji # UPDATED Dec 1 2023
  
      emoji_generator:
        !!python/name:material.extensions.emoji.to_svg # COPYRIGHT UPDATED Dec 1 2023


extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: |
  &copy; 2025 by <a href="https://github.com/plexoio"  target="_blank" rel="noopener">Frank Arellano</a> 
  with 
  <a href="https://www.mkdocs.org/"  target="_blank" rel="noopener">MkDocs</a>